Sending gaze coordinates to backend
anaya-s/FOCUS-frontend pull request #1
Opened 2024-12-04 00:35 UTC by Mahiethan

2024-12-04 00:44 UTC, Mahiethan commented
The gaze coordinates are being sent with the frame data.

When Webgazer doesn't detect a face, it stops producing gaze coordinates. Since the gaze data and frame data are produced together in the same callback function, no frames are sent to the backend if no face is detected.

I've made it so that if no face is detected (i.e. no coordinates produced), the frame data will still be sent with coordinates (x = 0, y = 0). This is done to make sure frame data is being continuously sent.

If this is OK with your backend stuff, please accept this review and merge it with main? Otherwise, let me know if you don't like this and want something else to happen.

2024-12-04 01:54 UTC, LewisArnold1 commented
Can we send null values instead?

2024-12-05 04:33 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
>        setFramesData((prevFrames) => [
use useCallback on sendVideoFrame

2024-12-05 04:40 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
> +  const sendVideoFrame = (xCoord, yCoord) => {
For line 54, lets redirect user to NotAuthorized Page ( in utils folder ) , moving forward I think we should do proper error handling for better use experience instead of doing console.error. ( dont worry i did this too )

2024-12-05 04:43 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
> +          sendVideoFrame(); // Send no coordinates with frame if face is not detected
might want to consider batching if we start sending more frames per second

2024-12-05 04:44 UTC, Mahiethan commented on focus-app/src/text_reader/Temp.jsx
>        setFramesData((prevFrames) => [
It is currently called inside webgazer.setGazeListener() (lines 109 - 118), which is already implemented as a callback function.

2024-12-05 04:48 UTC, Mahiethan commented on focus-app/src/text_reader/Temp.jsx
> +          sendVideoFrame(); // Send no coordinates with frame if face is not detected
No idea on the actual fps used to send frame. I am assuming its targetting the 60fps browser fps, but have to confirm in the backend with testing. But yh we can batch if we need > 60fps

2024-12-05 04:49 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
>    const [streamObtained, changeStatus] = useState(false);
lets keep naming convention consistent , start the function names for useState hooks with set

2024-12-05 04:51 UTC, Mahiethan commented on focus-app/src/text_reader/Temp.jsx
> +  const sendVideoFrame = (xCoord, yCoord) => {
Okay can do

2024-12-05 04:56 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
> +      <video ref={videoRef} autoPlay width="700" height="700" style={{display: 'none'}}></video>
can we just remove this line if we are not displaying the video ?

2024-12-05 05:00 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
>      webgazer.begin();
in the cleanup function, lets explictly close webgazer as well ( webgazer.end() )

2024-12-05 05:02 UTC, Mahiethan commented on focus-app/src/text_reader/Temp.jsx
>      webgazer.begin();
yep will do. Im planning to replace Temp.jsx with the demo text highlighting page so ill do it then.

2024-12-05 05:06 UTC, Mahiethan commented on focus-app/src/text_reader/Temp.jsx
> +      <video ref={videoRef} autoPlay width="700" height="700" style={{display: 'none'}}></video>
This is needed to obtain each frame while the video is running in the background.

2024-12-05 13:21 UTC, brandonaccessmemory commented on focus-app/src/text_reader/Temp.jsx
>        setFramesData((prevFrames) => [
oh i meant the useCallback() hook tho

2024-12-05 14:22 UTC, LewisArnold1 requested changes

2024-12-05 14:22 UTC, LewisArnold1 commented on focus-app/src/text_reader/Temp.jsx
>        setFramesData((prevFrames) => [
Agreed

2024-12-05 18:09 UTC, closed without merging